project_id = "ikqspsdqdunbvwawsvwq"

[functions.get-mapbox-token]
verify_jwt = false

[functions.geocode-venues]
verify_jwt = false

[functions.search-wine-places]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.robots-txt]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.analyze-wine]
verify_jwt = false
